app:
  jwtSecret: "======================VK==========================="
  jwtExpirationMs: "86400000"

server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vk
    username: postgres
    password: aboba

  clickhouse:
    datasource:
      url: jdbc:clickhouse://your-clickhouse-host:8123/your-database
      username: your-username
      password: your-password
