app:
  jwtSecret: "======================VK==========================="
  jwtExpirationMs: "86400000"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vk
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

echo:
  websocket:
    url: "wss://echo.websocket.org"
